// Keep the last explicitly selected vendor in direct npm dev/build runs.
// An empty VENDOR supplied by build.js is deliberately the neutral build.
const fs = require('node:fs');
const path = require('node:path');
const envFile = path.join(__dirname, 'src', 'environment-gen.ts');
const existing = fs.existsSync(envFile) ? fs.readFileSync(envFile, 'utf8') : '';
const previous = existing.match(/export const vendor: string = ['"]([^'"]*)['"]/u)?.[1];
let vendor = Object.hasOwn(process.env, 'VENDOR') ? process.env.VENDOR.trim().toLowerCase() : previous ?? 'galaxyxr';
if (vendor === 'neutral') vendor = '';
if (vendor !== '' && vendor !== 'galaxyxr') throw new Error(`Unsupported VENDOR: ${vendor}`);
const vendorUi = (process.env.VENDOR_UI ?? '').trim();
fs.mkdirSync(path.dirname(envFile), { recursive: true });
fs.writeFileSync(envFile, `// Auto-generated by generate-env.js - DO NOT EDIT\nexport const vendor: string = ${JSON.stringify(vendor)};\nexport const vendorUi: string = ${JSON.stringify(vendorUi)};\n`);
console.log(`Generated environment for ${vendor || 'neutral'}`);
