// Generated by tools/Generate-DriverDefaults.ps1 from Config.h and WriteInfo.
// Clone before editing. Migration stamps retain the native serializer defaults
// so newer stamps remain in settings.json instead of being pruned as defaults.
import type { Settings } from './types';

const nativeDefaults = {
  "debugMode": false,
  "galaxyXr": {
    "sdr10Baseline": false,
    "sdr10AllowEnhancements": false,
    "sdr10SettingsVersion": 1,
    "nativeIdentity": true,
    "renderModelVariant": "",
    "nativeInputProfile": false,
    "synthesizeGripTouch": true,
    "gripTouchThreshold": 0.03,
    "nativeResolution": true,
    "streamQuality": "balanced",
    "customEncodeWidth": 3072,
    "customStreamFormatWidth": 1536,
    "customBandwidthMbit": 350,
    "customStreamFormatWidthOverride": 0,
    "vrlinkHeadsetProfile": true,
    "profileMaxStreamFormatWidth": 0,
    "profileSupports10bit": true,
    "force10bit": false,
    "vrlinkDebugOverlay": false,
    "vrlinkMaxVideoQueueLatencyUs": 0,
    "vrlinkBackoffRecoveryCoefficient": 0.0,
    "renderModelScale": 1.15,
    "gripConvention": true,
    "handAnchorXCm": 0.0,
    "handAnchorYCm": 0.0,
    "handAnchorZCm": 0.0,
    "handAnchorPitchDeg": 0.0,
    "handAnchorYawDeg": 0.0,
    "handAnchorRollDeg": 0.0,
    "officialComponents": true,
    "controllerBypass": false,
    "simulateTouch": false,
    "aimTrimXCm": 0.0,
    "aimTrimYCm": -1.0,
    "aimTrimZCm": 1.0,
    "componentRebaseIncludeTrim": true,
    "meshOffsetXCm": 0.0,
    "meshOffsetYCm": 0.0,
    "meshOffsetZCm": 0.0,
    "skeletonOffsetXCm": 0.0,
    "skeletonOffsetYCm": 0.0,
    "skeletonOffsetZCm": 0.0,
    "skeletonOffsetMirror": true,
    "vrlinkExtraKeys": {}
  },
  "generalHeadset": {
    "useViveBluetooth": false
  },
  "customShader": {
    "enable": false,
    "enableForOther": false,
    "contrast": 50.0,
    "contrastMidpoint": 50.0,
    "contrastLinear": false,
    "contrastPerEye": false,
    "contrastPerEyeLinear": false,
    "contrastLeft": 50.0,
    "contrastMidpointLeft": 50.0,
    "contrastRight": 50.0,
    "contrastMidpointRight": 50.0,
    "saturation": 50.0,
    "gamma": 2.2,
    "subpixelShift": true,
    "disableMuraCorrection": false,
    "disableBlackLevels": false,
    "srgbColorCorrection": false,
    "srgbWhitePointCorrection": false,
    "srgbColorCorrectionMatrix": [],
    "dither10Bit": false,
    "enableFilterForOverlay": false,
    "enableFilterForDashboard": true,
    "samplingFilter": "None",
    "samplingFilterFXAA2SharpenStrength": 1.0,
    "samplingFilterFXAA2SharpenClamp": 0.05,
    "samplingFilterFXAA2CASStrength": 1.0,
    "samplingFilterFXAA2CASContrast": 1.0,
    "samplingFilterLumaSharpenStrength": 2.0,
    "samplingFilterLumaSharpenClamp": 0.1,
    "samplingFilterLumaSharpenPattern": 1,
    "samplingFilterLumaSharpenRadius": 1.0,
    "samplingFilterCASStrength": 1.0,
    "samplingFilterCASContrast": 1.0,
    "colorMultiplier": {
      "r": 1.0,
      "g": 1.0,
      "b": 1.0
    }
  },
  "forceTracking": false,
  "controllers": {
    "spaceVelocityFix": "off",
    "rotationOffsetDeg": {
      "x": 2.0,
      "y": -5.0,
      "z": -9.0
    },
    "positionOffsetCm": {
      "x": 0.5,
      "y": -1.5,
      "z": 0.5
    },
    "left": {
      "rotationOffsetDeg": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.0
      },
      "positionOffsetCm": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.0
      }
    },
    "right": {
      "rotationOffsetDeg": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.0
      },
      "positionOffsetCm": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.0
      }
    },
    "aligner": {
      "enable": false
    },
    "mirrorOffsetsForRightHand": true
  },
  "streamFrame": {
    "enable": false,
    "saturation": 50.0,
    "vibrance": 0.0,
    "contrast": 50.0,
    "contrastMidpoint": 50.0,
    "contrastLinear": false,
    "gamma": 2.2,
    "colorMultiplier": {
      "r": 1.0,
      "g": 1.0,
      "b": 1.0
    },
    "srgbMatrix": [],
    "fxaa": "off",
    "cas": {
      "enable": false,
      "strength": 0.5,
      "perEye": false,
      "strengthLeft": 0.5,
      "strengthRight": 0.5
    },
    "postPack": {
      "enable": true,
      "casEnable": true,
      "foveaStrength": 0.6,
      "peripheryStrength": 0.3,
      "foveaTop": true,
      "edgeFalloff": 0.12,
      "limitedRange": true
    },
    "dither": false,
    "blackFloor": {
      "rampBar": false,
      "rangeMode": "off",
      "shadowLift": false,
      "floorCode": 2.0,
      "kneeCode": 8.0,
      "blackPointCode": 0.0
    },
    "stationaryDimming": {
      "enable": false,
      "movementThreshold": 0.4,
      "movementTime": 15.0,
      "dimSeconds": 10.0,
      "brightenSeconds": 1.0
    },
    "k1": 0.0,
    "k2": 0.0,
    "distortion": {
      "mode": "k1k2",
      "points": [],
      "gain": 1.0,
      "centerTune": {
        "enable": false,
        "breatheAmp": 0.05
      },
      "tune": {
        "enable": false,
        "rate": 0.08,
        "stepSize": 0.0,
        "ringOpacity": 0.55,
        "forceGrid": true,
        "segments": 1,
        "segmentLayout": [],
        "bands": [
          0.15,
          0.22,
          0.3,
          0.38,
          0.46,
          0.55,
          0.65
        ]
      },
      "perEye": false,
      "perAxis": false,
      "curves": {},
      "segments": 1,
      "annulus": {
        "enable": false,
        "rMin": 0.0,
        "rMax": 0.75,
        "feather": 0.05
      }
    },
    "centerOffsetXLeft": 0.0,
    "centerOffsetXRight": 0.0,
    "centerOffsetY": 0.0,
    "alignment": {
      "leftH": 0.0,
      "leftV": 0.0,
      "rightH": 0.0,
      "rightV": 0.0
    },
    "skipColorWhileDashboardOpen": false,
    "processAtSubmitLayer": false,
    "poseLogging": false,
    "poseLogBurst": false,
    "syncTimeoutMs": 10,
    "reconLogger": false,
    "hitchDiag": false,
    "deferredEviction": true,
    "directRender": true,
    "zeroCopy": false,
    "eyeGaze": {
      "debugRing": false,
      "tanHalfFovX": 1.19,
      "tanHalfFovY": 1.19,
      "predictionMs": 30.0,
      "debugGrid": false,
      "gridMode": "uv",
      "gridAngularDeg": 2.5,
      "calibDot": false,
      "probeCapture": false,
      "gridWorldLocked": false,
      "gridOpaque": false,
      "swimProbe": false,
      "overlayWarped": false
    },
    "pupilSwim": {
      "centerStrengthX": 0.0,
      "centerStrengthY": 0.0
    },
    "zeroCopyV3": false,
    "nvencTap": true,
    "nvencBandwidthOverrideMbit": 0,
    "nvencSettingsVersion": 0,
    "nvencFixLevel": true,
    "nvencBitrateMbit": 0,
    "nvencMaxQp": 0,
    "nvencAqStrength": 0,
    "nvencMaxBitrateHeadroomPct": 0,
    "nvencVbvFrames": 2,
    "nvencForceFps": 90,
    "nvencBitrateScale": true,
    "nvencVrlinkClampMbit": 350,
    "nvencPreset": 0,
    "nvencPresetMerge": true,
    "nvencVuiFullRange": -1,
    "nvencMinQp": 0,
    "nvencMinQpIntra": 0,
    "nvencForceCbr": true,
    "nvencLowDelayKfScale": 2,
    "nvencVuiMatrix": -1,
    "nvencVuiPrimaries": -1,
    "nvencVuiTransfer": -1,
    "nvencSplitMode": 1,
    "nvencQpFovea": 0,
    "nvencQpPeriphery": 0,
    "nvencVerbose": false,
    "gameLinkLinearVelocityCutoff": 0.05,
    "gameLinkAngularVelocityCutoffDeg": 10.0,
    "controllerSmoothingHz": 6.0,
    "streamFrameSchema": 1,
    "graveyardEnable": false,
    "brightness": 1.0
  },
  "takeCompositorScreenshots": false,
  "onlyHandlePrivateFunctionality": false,
  "watchDistortionProfiles": true
};

export const driverDefaults: Settings = nativeDefaults;
