param([switch]$Check)
# Regenerate the GUI's offline defaults from the real native Config constructors
# and WriteInfo serializer. No driver, SteamVR, or user configuration is loaded.
$ErrorActionPreference = 'Stop'
$repo = Split-Path $PSScriptRoot -Parent
. (Join-Path $PSScriptRoot 'Enter-PortableBuildEnvironment.ps1')
$loader = Get-Content -Raw -LiteralPath (Join-Path $repo 'GalaxyXRDriver/src/Config/ConfigLoader.cpp')
$config = Get-Content -Raw -LiteralPath (Join-Path $repo 'GalaxyXRDriver/src/Config/Config.h')
$base = [regex]::Match($loader, '(?s)ordered_json baseHeadsetInfo\(.*?(?=void ConfigLoader::WriteInfo\()').Value
$defaults = [regex]::Match($loader, '(?s)\{"defaultSettings", \{(.*?)\r?\n\s*\}\},\r?\n\s*\{"builtInDistortionProfiles"').Groups[1].Value
$galaxy = [regex]::Match($config, '(?s)struct GalaxyXrConfig\{(.*?)\r?\n\};').Groups[1].Value
if (-not $base -or -not $defaults -or -not $galaxy) { throw 'Native serializer structure changed; inspect the generator extraction boundaries.' }
# Galaxy XR is not currently published by WriteInfo. Read its scalar member
# names from Config.h; their values still come from the compiled constructor.
$galaxy = [regex]::Replace($galaxy, '//[^\r\n]*', '')
$members = @([regex]::Matches($galaxy, '(?m)^\s*(?:bool|int|double|std::string)\s+(\w+)\s*=') | ForEach-Object { $_.Groups[1].Value } | Select-Object -Unique)
if ($members.Count -lt 30 -or -not ($members -contains 'nativeIdentity')) { throw 'Galaxy XR member extraction failed.' }
$galaxyFields = ($members | ForEach-Object { 'defaults["galaxyXr"]["' + $_ + '"] = defaultSettings.galaxyXr.' + $_ + ';' }) -join "`n"
$source = @"
#include <iostream>
#include <nlohmann/json.hpp>
#include "Config.h"
using nlohmann::json;
using nlohmann::ordered_json;
$base
int main() {
    Config defaultSettings = {};
    ordered_json defaults = {$defaults
    };
    $galaxyFields
    defaults["galaxyXr"]["vrlinkExtraKeys"] = json::object();
    defaults["streamFrame"]["brightness"] = defaultSettings.streamFrame.brightness;
    defaults["controllers"]["mirrorOffsetsForRightHand"] = defaultSettings.controllers.mirrorOffsetsForRightHand;
    // Retained GUI schema field; native directory watching is unconditional.
    defaults["watchDistortionProfiles"] = true;
    std::cout << defaults.dump(2) << std::endl;
}
"@
$build = Join-Path $repo 'build/driver-defaults-generator'
New-Item -ItemType Directory -Force -Path $build | Out-Null
$cpp = Join-Path $build 'defaults.cpp'
$exe = Join-Path $build 'defaults.exe'
[IO.File]::WriteAllText($cpp, $source, [Text.UTF8Encoding]::new($false))
& cl.exe /nologo /EHsc /std:c++17 /MT /DVENDOR_GALAXYXR ("/I" + (Join-Path $repo 'ThirdParty/json/include')) ("/I" + (Join-Path $repo 'GalaxyXRDriver/src/Config')) ("/Fo" + (Join-Path $build 'defaults.obj')) ("/Fe" + $exe) $cpp
if ($LASTEXITCODE -ne 0) { throw 'Native defaults compilation failed.' }
$json = (& $exe) -join "`n"
if ($LASTEXITCODE -ne 0) { throw 'Native defaults generation failed.' }
$parsed = $json | ConvertFrom-Json
if ($parsed.galaxyXr.nativeIdentity -ne $true -or $parsed.streamFrame.nvencSettingsVersion -ne 0 -or $parsed.streamFrame.streamFrameSchema -ne 1) { throw 'Native vendor/default migration sentinel verification failed.' }
$text = @"
// Generated by tools/Generate-DriverDefaults.ps1 from Config.h and WriteInfo.
// Clone before editing. Migration stamps retain the native serializer defaults
// so newer stamps remain in settings.json instead of being pruned as defaults.
import type { Settings } from './types';

const nativeDefaults = $json;

export const driverDefaults: Settings = nativeDefaults;
"@ + "`n"
$target = Join-Path $repo 'GalaxyXRDriverGUI/src-lit/domain/driver-defaults.ts'
if ($Check) {
    if (-not (Test-Path -LiteralPath $target) -or ([IO.File]::ReadAllText($target) -replace "`r`n", "`n") -cne ($text -replace "`r`n", "`n")) { throw 'GUI defaults differ from the native definitions. Run tools/Generate-DriverDefaults.ps1.' }
    Write-Output 'Native/GUI offline defaults match.'
} else {
    [IO.File]::WriteAllText($target, $text, [Text.UTF8Encoding]::new($false))
    Write-Output "Generated $target"
}
