// Temporary re-export shim for the parallel-development phase only.
// During the cutover, src-lit/ is promoted to src/ and this file is deleted;
// the canonical environment (vendor flags + driver name) lives in src/environment.ts
// with src/environment-gen.ts generated by generate-env.js (unchanged contract).
export * from '../src/environment';
